phrase/openapi

Makefile
clients/cli/cmd/internal/pull.go
clients/cli/go.mod
clients/cli/go.sum
openapi-generator/templates/cli/api.handlebars
openapi-generator/templates/cli/go.mod.mustache

Use the latest version of the phrase-go lib

CLI: Update phrase-go to 1.0.8

---

openapi-generator/templates/typescript-fetch/apis.mustache
openapi-generator/typescript_lang.yaml

We need to return the API response even when there is no return type

Typescript: Always return server response

---

doc/rapidoc.scss

https://trello.com/c/QhCNIuu4/778-docs-no-operations-headers-in-safari
CSS load order in Safari is different that's why it was invisible only there.

Show operations headers in Safari

---

openapi-generator/php_lang.yaml
schemas/account.yaml
schemas/project.yaml

It is already exposed in the API just not documented and therefore the slugs are not available in the API clients

Add slug to account and project

---

schemas/job.yaml

Required for an account-wide jobs endpoint.

Jobs: Add project to job results

---

openapi-generator/templates/ruby-client/api_client_typhoeus_partial.mustache

Currently only File objects are supported but when scripting uploads, we often use Tempfiles instead.

Ruby: Support sending Tempfile objects

---

paths/keys/search.yaml
paths/translations/search.yaml

We recently dropped support for Link-headers in POST requests so we should reflect that in the API documentation.

Remove Link headers from POST requests

---

paths/webhooks/create.yaml
paths/webhooks/update.yaml

Webhooks can now have a custom secret to override the project-wide secret.

Add secret to webhooks

---

openapi-generator/templates/cli/README.handlebars
openapi-generator/templates/cli/README.mustache

Readme links were not working anymore: https://github.com/phrase/phrase-cli/issues/52

Fix CLI installation help links

---

openapi-generator/templates/ruby-client/api_client_faraday_partial.mustache
openapi-generator/templates/ruby-client/api_client_typhoeus_partial.mustache

Nested objects in POST requests seem broken since objects are not properly serialized when generating the request body. This causes wrong requests, e.g. when submitting `format_options` since the hash is only sent as a string.
Before:
--------------------------b8e580af624e881d
Content-Disposition: form-data; name="format_options"
{:ignore_source_translations=>true}
--------------------------b8e580af624e881d--
After:
--------------------------7f6d8be7b2cfe386
Content-Disposition: form-data; name="format_options[ignore_source_translations]"
true
--------------------------7f6d8be7b2cfe386--
It's not an ideal solution but fixes the issue. For the future we can think about moving all format options to first-class form params of the upload endpoint in the OpenAPI specification.

Ruby-Client: Support nested objects/hashes in form data

---

paths/webhooks/create.yaml
paths/webhooks/update.yaml
schemas/webhook.yaml

Webhooks now feature the new "include_branches" option that lets you define if webhooks should also be triggered for events that happen inside a branch of the project.

Add 'include_branches' option for webhooks

---

.github/workflows/build.yml

The idea is to read the phrase-go version from `README.md` and try to create a tag with this version.
If the tag already exists, it will not be created twice. Then we push to `phrase/phrase-go` with tags and for new tag the pipeline will start automatically.

auto-tag go releases

---

paths/invitations/create.yaml
paths/invitations/update.yaml
schemas/invitation.yaml

Allow default_locale_codes parameter for invitations#create/update in API as we have it in our frontend already.
https://github.com/phrase/phrase/pull/7302

Api default locale codes invitations WORKFLOWS-409

---

paths/screenshot_markers/create.yaml
paths/screenshot_markers/destroy.yaml
paths/screenshot_markers/index.yaml
paths/screenshot_markers/show.yaml
paths/screenshot_markers/update.yaml
paths/screenshots/create.yaml
paths/screenshots/destroy.yaml
paths/screenshots/index.yaml
paths/screenshots/show.yaml
paths/screenshots/update.yaml

Allow passing "branch" name since we now support branches in the Screenshots API.

Add support for branching in Screenshots API

---

clients/cli/cmd/internal/upload_cleanup.go
doc/compiled.json
openapi-generator/go_lang.yaml
paths.yaml
paths/keys/destroy-collection.yaml
paths/translations/batch_exclude.yaml
paths/translations/batch_include.yaml
paths/translations/batch_review.yaml
paths/translations/batch_unverify.yaml
paths/translations/batch_verify.yaml

Batch and single resource endpoints are mapped on the same client action. This will make the batch actions unusable.
In the old client we supported:
```
$ phrase keys delete
```
and 
```
$ phrase key delete
```
In the new client only the plural command is currently supported. This cause `phrase keys delete` is now longer unique and working as expected  https://phraseapp.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=INTEGRATE&modal=detail&selectedIssue=INTEGRATE-647
This PR solves this by introducing `-collection` commands.

list actions has own ids to make client working

---

openapi-generator/go_lang.yaml
openapi-generator/templates/go/client.mustache

Response should not be used in case of an error. Reported in https://github.com/phrase/phrase-go/pull/5

Fix error handling in callAPI

---

.github/workflows/build.yml
clients/cli/build/go_build.sh
clients/cli/go.mod
openapi-generator/cli_lang.yaml

With the release of go 1.16 we can now provide binaries for M1 Macs

CLI: Release binary for M1 Macs

---

clients/cli/.github/workflows/release.yml
clients/cli/build/config.sh

Required to update the go version in the phrase-cli repo

Update to go 1.16 for M1 builds

---

clients/cli/cmd/internal/pull.go
openapi-generator/go_lang.yaml
openapi-generator/ruby_lang.yaml
openapi-generator/templates/cli/api.handlebars
openapi-generator/templates/go/client.mustache
paths/locales/download.yaml

Return file handlers for locale download to be consistent between formats and better handle binary formats

Change response type for locale downloads

---

clients/cli/cmd/internal/pull.go
openapi-generator/cli_lang.yaml

The function `client.LocalesApi.LocaleDownload` does not create files if there is nothing to write (see https://github.com/phrase/phrase-go/blob/660264e0c1a322325cc83bf42da67b851514c762/client.go#L456). This also means that they cannot be cleaned up.
As we did not check the `err` part of `ioutil.ReadAll(file)` we also did not notice that file was still an uninitialized pointer.
Even though this now works (in case of an uninitialized os.File we now just write the empty byte slice) we should think of changing `client.LocalesApi.LocaleDownload` (as this would probably break the API we might need to add a new function) so that we can e.g. provide an `io.Reader` and so the caller can decide if to actually create a file or maybe if a buffer is also good enough.

make sure to only cleanup file if it is actually initialized

---

schemas/invitation.yaml
schemas/member.yaml
schemas/member_project_detail.yaml

This pull request adds missing type declarations to `date-time` fields. This created an `AnyType` issue in the generated `phrase-js` project (also reported here https://github.com/phrase/phrase-js/issues/9).

Fix build of phrase-js by adding missing type declarations to date-time field

---

paths/keys/exclude.yaml
paths/keys/include.yaml

Make it more obvious in the examples that `target_locale_id` is a required parameter.

Adjust key exclude/include examples to include target_locale_id

---

openapi-generator/templates/php/api.mustache

`\GuzzleHttp\Psr7\try_fopen` and `\GuzzleHttp\Psr7\build_query` does not exists anymore on the last GuzzleHttp version

UploadAPI error : fix by using new Utils::tryFopen and Query::build methods

---

clients/cli/go.mod
openapi-generator/cli_lang.yaml

Release a new version of Phrase CLI (includes job templates API)

Bump Phrase CLI to 2.2.0

---

paths/accounts/locales.yaml

Account id was missing in the definition
Thanks https://github.com/phrase/openapi/pull/139 for the hint

Add missing account id

---

openapi-generator/ruby_lang.yaml
paths/locales/download.yaml

Add the `source_locale_id` to the download.yml so that it can be used by the XTM sync in the phrase-ruby library as well as documented in our OpenAPI.

Add `source_locale_id` to download.yml

---

paths/translations/batch_verify.yaml

These two are not actual parameters.

Remove `sort` and `order` from docs for `batch_verify` endpoint

---

openapi-generator/templates/php/api.mustache

On UploadApi and create method, params `format_options` and `locale_mapping` cannot be sent due to a fatal error.
So now, for example, we can pass ['my_option' => 'my-value'] as format_options argument and it will send as :
name `format_options[my_option]` and contents `my-value`.

phrase-php: Fix upload_create object params was not correctly sent

---

clients/cli/build/release.sh

Passing token as query param is deprecated

Fix CLI release script

---

clients/ruby/lib/phrase/response.rb
openapi-generator/ruby_lang.yaml
openapi-generator/templates/ruby-client/gemspec.mustache

Update link-header-parser dependency and restrict to use with Ruby 2.6+ which is required by link-header-parser.

Add support for Ruby 3

---

clients/cli/cmd/internal/upload_cleanup.go
clients/cli/cmd/upload_cleanup.go
openapi-generator/cli_lang.yaml

Add project_id flag for `uploads cleanup` command in cases in which there is no `.phrase.yml` config or the config does not contain a default project id

CLI: Add project_id to uploads cleanup command

---

clients/cli/cmd/internal/upload_cleanup.go
openapi-generator/cli_lang.yaml

It's using the wrong project id if a manual project id is provided. Missed adding it here: https://github.com/phrase/openapi/pull/173

CLI: Use correct project id for upload cleanup

---

clients/cli/cmd/internal/init.go

We need to pass a pointer to allow setting a project name

Fix project create by passing pointer to prompt

---

doc/compiled.json
openapi-generator/go_lang.yaml
openapi-generator/templates/cli/api.handlebars
paths/screenshots/create.yaml

The templates for the CLI did not handle cases correctly in which a parameter starts with `file` like `filename` or `fileencoding`. Now files should be opened and non-file types treated correctly as well. In addition, changing the screenshots content-type to `multipart/form-data`

Fix uploading screenshots via CLI

---

clients/cli/go.mod
clients/cli/go.sum
openapi-generator/cli_lang.yaml

Release new CLI version with fixes from https://github.com/phrase/openapi/pull/199

Bump phrase-cli to 2.4.8

---

openapi-generator/python_lang.yaml
openapi-generator/templates/python/api_client.mustache

Support Python 3 when writing locale files.
Fix from https://github.com/phrase/phrase-python/pull/4

python: support Python 3 for downloading locales

---

clients/cli/cmd/init.go
clients/cli/cmd/internal/init.go
openapi-generator/cli_lang.yaml

Use `host` and `access_token` args when calling `phrase init --host <host> --access_token <token>`

CLI: Fix passing in host as CLI argument

---

doc/compiled.json
paths/branches/merge.yaml

Change strategy name from "use_master" to "use_main".
API still supports the deprecated name: https://github.com/phrase/phrase/pull/9750

Adjust branching merge strategy name

---

openapi-generator/templates/go/model.mustache
schemas/translation.yaml

Currently it's not possible to send an empty translation which might be important if we want to use a machine translation later.
This removes the `omitempty` option from the `content` field by providing a custom JSON options via `x-json-tag`.
I changed the template to the intent. So the tag now provides a replacement.
This is how a generated model looks like:
```
package phrase
import (
"time"
)
// Translation struct for Translation
type Translation struct {
Id           string        `json:"id,omitempty"`
Content      string        `json:"content"`
Unverified   *bool         `json:"unverified,omitempty"`
Excluded     *bool         `json:"excluded,omitempty"`
PluralSuffix string        `json:"plural_suffix,omitempty"`
Key          KeyPreview    `json:"key,omitempty"`
Locale …
```

Allow empty translation content to be send

---

doc/compiled.json
openapi-generator/go_lang.yaml
paths.yaml

Fix invalid paths, which contained `team_id`, but should just be `id` as this is the resource we're accessing
Reported in https://github.com/phrase/phrase-go/issues/10

Use correct id in path for teams

---

openapi-generator/templates/php/model_generic.mustache

solves #225 
Fixes `Deprecated: Return type of Phrase\\Model\\Locale::offset*($offset) should either be compatible with ArrayAccess::offset*(mixed $offset): void, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice` deprecation with PHP 8.1.

Fix PHP 8.1 deprecations

---

clients/cli/build/build.sh

Currently the Linux arm64 release is only available as a binary and not as an archive, this will save some transfer bytes.

Create tar.gz archive for Linux arm64 as well

---

clients/cli/.github/workflows/release.yml
clients/cli/Dockerfile
clients/cli/build/release.sh

Pushing the image twice is overwriting the previous image. Instead both platforms needs to used in a single build/push command

Fix linux/arm64 Docker build

---

clients/cli/cmd/internal/paths/paths.go
openapi-generator/cli_lang.yaml

https://memsource.tpondemand.com/entity/84434-phrase-cli-error-because-of-messages
Not sure why this check was here in the first place. Unfortunately, git blame is not very informative and there are no specs covering this validation.
Currently I see no drawbacks in removing this check.

Allow pushing files without extensions

---

clients/cli/build/config.sh

The release of the current version failed to  an outdated go version used in the build: https://github.com/phrase/phrase-cli/actions/runs/4084033929/jobs/7040257981

Update CLI go build version

---

doc/compiled.json
paths/keys/exclude.yaml
paths/keys/include.yaml
paths/keys/search.yaml
paths/keys/tag.yaml
paths/keys/untag.yaml
paths/search/in_account.yaml
paths/translations/batch_exclude.yaml
paths/translations/batch_include.yaml
paths/translations/batch_review.yaml
paths/translations/batch_unverify.yaml
paths/translations/batch_verify.yaml
paths/translations/search.yaml

In many CLI examples the query parameter was named `query` instead of `q`, which is invalid

Fix query parameter name in CLI examples

---

clients/ruby/.github/workflows/release.yml

Ruby 2.6 cannot be found anymore: https://github.com/phrase/phrase-ruby/actions/runs/4229987197/jobs/7346857566

phrase-ruby: Update Ruby version for release

---

clients/go/.goreleaser.yaml

Should prevent errors like https://github.com/phrase/phrase-go/actions/runs/4261776439/jobs/7416491671

Add .goreleaser.yaml file

---

clients/cli/build/go_build.sh

Build was failing likely due to a git version mismatch of the GitHub runner and go Docker image. Disable `buildvcs` to attempt to fix it: https://github.com/phrase/phrase-cli/actions/runs/4263384954/jobs/7420054269

CLI: Set buildvcs to false to fix build

---

clients/cli/.github/workflows/release.yml

Update to latest action to check whether it helps with the current failing release action: https://github.com/phrase/phrase-cli/actions/runs/4283697647/jobs/7459778153
Fixes: https://github.com/dawidd6/action-homebrew-bump-formula/issues/51

Use latest bump brew action

---

.github/workflows/lint.yml

Disabling the compile check for the CLI for now. This step fails when for example a new endpoint is being added as we first need to release a new version of phrase-go for the cli to compile

fix: disable compile check

---

clients/cli/go.mod
clients/cli/go.sum
openapi-generator/cli_lang.yaml

Release CLI version 2.7.0 with GJT endpoints, following #281

Release CLI 2.7.0

---

doc/compiled.json
openapi-generator/go_lang.yaml
openapi-generator/java_lang.yaml
openapi-generator/php_lang.yaml
openapi-generator/python_lang.yaml
openapi-generator/ruby_lang.yaml
openapi-generator/typescript_lang.yaml
paths/icu/skeleton.yaml

The endpoint for building ICU skeletons has a previously undocumented parameter `cldr_version` which determines the pluralization version used.

Expose previously undocumented cldr_version parameter #TSI-1717

---

doc/compiled.json
paths/job_comments/create.yaml
paths/job_comments/destroy.yaml
paths/job_comments/index.yaml
paths/job_comments/show.yaml
paths/job_comments/update.yaml

We use cli v2 examples to generate docker comments for phrase cli.
Fix to use correct one.

Fix the CLI example for job comments

---

doc/compiled.json
paths/jobs/add_keys.yaml
paths/jobs/remove_keys.yaml

We are using the CLI examples to generate Orchestrator actions. This PR fixes the above-mentioned ones.
co-authored by @cschmatzler

Correct "Add keys to job" and "Remove keys from job" CLI example

---

clients/cli/cmd/internal/pull.go
openapi-generator/cli_lang.yaml

Fix waiting until rate limit timeout is reset and update waiting time dynamically
[Screencast from 2023-05-31 15-51-36.webm](https://github.com/phrase/openapi/assets/1757301/a327034c-ca79-4955-bbd9-7a8593de87d4)

CLI: Fix waiting for rate limit reset

---

clients/cli/cmd/internal/print/print.go
clients/cli/cmd/internal/pull.go
openapi-generator/cli_lang.yaml

Print rate limit warning as JSON when `batch` mode is enabled. Timer is also no updated inline anymore as the color printing was interfering with that

CLI: Fix batch printing for ratelimit message

---

openapi-generator/templates/typescript-fetch/apis.mustache
openapi-generator/templates/typescript-fetch/runtime.mustache

Addresses https://github.com/phrase/phrase-js/issues/16
`flattenDeepParams` implementation heavily inspired by https://github.com/rails/rails/blob/7-0-stable/activesupport/lib/active_support/core_ext/object/to_query.rb

fix(typescript): Serialize deep FormData parameters [TSI-1895]

---

clients/cli/go.mod
clients/cli/go.sum

Addresses https://github.com/Homebrew/homebrew-core/pull/140271

fix(cli): Bump go library version

---

clients/go/.goreleaser.yaml

`replacements` parameter has been deprecated and removed by `goreleaser`, so our release process was broken for some time.
https://goreleaser.com/deprecations/#archivesreplacements
https://github.com/phrase/phrase-go/actions/runs/5962357481/job/16173405854
I am not sure though if the `name_template` is equivalent as given. Not even sure whether that section is used at all in case of libraries or not, as we are releasing source code only, no binaries.

fix(go): Update goreleaser config

---

doc/compiled.json
paths/comment_replies/index.yaml
paths/comments/index.yaml

- Document new query parameters
https://github.com/phrase/phrase/pull/11643
https://memsourcegroup.atlassian.net/browse/TSE-869

feat(API): Document new query parameters

---

clients/cli/go.mod
release-please/config-go.json

Try automating phrase-go version bump for CLI using https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-files

build(CLI): Automatically update go-phrase version in CLI

---

doc/index.html

Avoid confusing users with descriptions collapsed by default and not being obvious that they can be expanded
https://phrase.atlassian.net/browse/TSI-2024

docs: Expand multiline descriptions by default [TSI-2024]

---

doc/compiled.json
parameters.yaml
paths.yaml
paths/figma_attachment_keys/create.yaml
paths/figma_attachment_keys/destroy.yaml
paths/figma_attachments/create.yaml
paths/figma_attachments/destroy.yaml
paths/figma_attachments/index.yaml
paths/figma_attachments/show.yaml
paths/figma_attachments/update.yaml
schemas.yaml
schemas/figma_attachment.yaml

- https://phrase.atlassian.net/browse/TSE-613
- https://github.com/phrase/phrase/pull/11856

feat(API): Implement figma attachments endpoints

---

doc/compiled.json
schemas/job_details.yaml

Fixed example data for get a single job spec.
There is actual response, the source locale is object, not array.
```
{
"id": "5dabeecef237159f189b2af75b8da44c",
"name": "Translations from 2023-10-18",
"owner": {
"id": "b233e...",
"username": "Maksym...",
"name": "Maksym..."
},
"briefing": "",
"job_tag_name": "job-12B309E9",
"due_date": "2023-10-25T11:00:00Z",
"state": "draft",
"ticket_url": "",
"project": {
"id": "87d8b621...",
"name": "test",
"main_format": "",
"created_at": "2023-07-19T12: 10: 01Z",
"updated_at": "2023-10-18T13: 51: 50Z"
},
"branch": null,
"created_at": "2023-10-18T13: 51: 50Z",
"updated_at": "2023-10-18T13: 51: 50Z",
"source_locale": {
"id": "0f4bc54...",
"name": "en",
"code": "en"
},
"locales": [],
"keys": [],
"locked": false
}
```

docs: Correct example data for get a single job spec

---

.github/workflows/test-java.yml
clients/java/src/test/java/com/phrase/client/api/LocalesApiTest.java
doc/compiled.json
openapi-generator/templates/java/build.gradle.mustache
openapi-generator/templates/java/libraries/okhttp-gson/ApiClient.mustache
openapi-generator/templates/java/libraries/okhttp-gson/api.mustache
paths/locales/download.yaml

Some assumptions made while working on the PR:
- `format_options` argument will be key-value based map with values mostly being of primitive types
- Initially explored the possibility of using params with `style` `deepObject` and `explode: true` option as suggested [here](https://stackoverflow.com/questions/48491688/how-to-define-parameters-with-square-brackets-in-openapi-swagger/48498055#48498055) as a fix but subsquently wasn't able to find appropriate mustache directive to determine if the param has any of these attributes (deepObject, explode: true) which led to adding a fix by checking if input is of the type Map and if yes, manually convert it to key value based `Pair` objects.
Phrase API accepts `format_options` argument on [locales …

feat: [TSI-2083] enable format_options argument for java-client  

---

clients/cli/cmd/internal/pull.go

Now when there's an error on CLI pull, the users are left in dark as the server response (which usually explains the reason for the error) is not printed out. This PR addresses that.
https://phrase.atlassian.net/browse/TSI-1750
Related: https://github.com/phrase/phrase-cli/issues/126

feat(CLI): On pull error, print the API response [TSI-1750]

---

doc/compiled.json
paths/keys/create.yaml
paths/keys/update.yaml
schemas/translation_key_details.yaml

update translation key create/update with custom metadata. Also. add CM in translation key schema response
response CM in translation key
Update/Create CM on translation key
https://github.com/phrase/openapi/assets/108525179/cecd517f-6d0e-42fc-a172-812c80612d69
https://phrase.atlassian.net/browse/TSS-2504

feat: update translation key create/update with custom metadata. Add CM schema in translation key response

---

doc/compiled.json
schemas/upload.yaml

Adds `url` field to upload payload, so that users can easily visit the Phrase App and see the corresponding upload

feat(API): Add url field to uploads [TSI-1735]

---

openapi-generator/templates/cli/api.handlebars

seems that https://github.com/phrase/openapi/pull/199/files#diff-cf7b4bb3c2d75383f6a3126d13a8ded9303fe36224c090daa1d9f29a5c75fdf5R71 broke the syntax of the generated API modules for CLI, resulting with: https://github.com/phrase/openapi/actions/runs/7194539626/job/19595281387
This fixes at least syntactic part of it.

build(CLI): Fix broken API template

---

.github/workflows/build.yml
openapi-generator/templates/java/README.mustache

Fix creating tags for new PHP and Java releases by setting `PACKAGE_VERSION`

chore: fix creating tags for PHP and Java

---

clients/cli/cmd/internal/push.go

Several smaller improvements on push errors:
* Print error response from server on upload create
* Print link to the upload upon upload processing error (the response does not contain more info)
* Return non-zero exit code when any of the uploads were not processed successfully (https://github.com/phrase/phrase-cli/issues/135)

feat(CLI): Improve push error display [TSI-1736]

---

openapi-generator/templates/java/libraries/okhttp-gson/pom.mustache

https://github.com/phrase/phrase-java/actions/runs/7220213663/job/19672689047
Seems that parallel test execution doesn't work well with HTTP request mocking

build(java): Disable parallel test execution

---

clients/go/test/api_locales_test.go
clients/go/test/api_uploads_test.go
openapi-generator/templates/go/api.mustache
openapi-generator/templates/go/client.mustache
paths/uploads/create.yaml

Format Options with nested properties/map was not being properly serialized in the upload creation request.
This PR adds a custom method to serialize the nested format_options appropriately as a part of the request.
Related Issue: https://phrase.atlassian.net/browse/TSI-2192

fix(GO): Fix format_option serialization when creating upload

---

.github/workflows/build.yml

https://github.com/phrase/openapi/actions/runs/7244950008/job/19734096647
Java build fails with:
```
no changes added to commit (use "git add" and/or "git commit -a")
[master a0da195] Deploying from  phrase/openapi@bd04c74f
205 files changed, 206 insertions(+), 206 deletions(-)
remote: 
remote: GitHub found 2 vulnerabilities on phrase/phrase-java's default branch (1 high, 1 moderate). To find out more, visit:        
remote:      https://github.com/phrase/phrase-java/security/dependabot        
remote: 
To https://github.com/phrase/phrase-java.git
85688b4..a0da195  master -> master
! [rejected]        1.18.0 -> 1.18.0 (already exists)
error: failed to push some refs to 'https://github.com/phrase/phrase-java.git'
hint: Updates were rejected because the tag already exists in the remote.
```

build: Clone whole history when pushing PHP and Java clients

---

openapi-generator/templates/go/client.mustache

Previously merged #498 didn't trigger release for CLI, since the fix was meant for the CLI, this additional PR aims to retrigger it by generating a separate PR for CLI once merged.

fix(GO,CLI): Retrigger Go & CLI release.

---

README.md
clients/go/test/api_custom_metadata_test.go
clients/go/test/api_locales_test.go
clients/go/test/api_uploads_test.go
doc/compiled.json
paths/custom_metadata_properties/create.yaml
paths/custom_metadata_properties/update.yaml
schemas/custom_metadata_data_type.yaml

Update Custom Metadata non-GET endpoints so that they comply with our standard way of passing parameters.

fix(API): Create Custom Metadata endpoint fix [TSI-2222]

---

clients/go/test/api_uploads_test.go
openapi-generator/templates/cli/api.handlebars
openapi-generator/templates/go/client.mustache

In a previous PR the assumed type of nested arg was a map with string keys and interface typed values which raised mismatch error. This PR fixes it by asserting keys to be of type interface as well.
fix(GO): fix type mismatch error
fix(CLI): retrigger release for GO

fix(GO): fix type mismatch for nested args

---

openapi-generator/templates/java/README.mustache
openapi-generator/templates/java/api_doc.mustache
openapi-generator/templates/java/libraries/jersey2-experimental/api_doc.mustache
openapi-generator/templates/java/libraries/jersey2/api_doc.mustache
openapi-generator/templates/java/libraries/okhttp-gson/api_doc.mustache

Our API expects `token` as a token prefix, so correcting the examples to show that.

docs(Java): Correct token prefix

---

doc/compiled.json
paths/custom_metadata_properties/index.yaml

Document `q` param to filter custom metadata properties by name.

feat: add query param for properties

---

doc/compiled.json
lint.sh
main.yaml
parameters.yaml
paths.yaml
paths/repo_syncs/activate.yaml
paths/repo_syncs/deactivate.yaml
paths/repo_syncs/events.yaml
paths/repo_syncs/export.yaml
paths/repo_syncs/history.yaml
paths/repo_syncs/import.yaml
paths/repo_syncs/index.yaml
paths/repo_syncs/show.yaml
schemas.yaml
schemas/repo_sync.yaml
schemas/repo_sync_event.yaml

feat(API): Add Repo Sync [TSI-1923]

---

openapi-generator/templates/java/pom.mustache

In an earlier PR #534 to allow nullable values, a dependency in Java client was introduced, ever since it being merged, build on `java-client` repo has been failing complaining about missing dependency.
Possible reason can be, we use `gradle` within OpenApi whereas `java-client` uses `maven` and the said dependency had to be included in the `pom.xml` file as well. For now have added the dependency to `pom.mustache` with the latest release version.
[Link to failed builds on java-client](https://github.com/phrase/phrase-java/actions/runs/7781883827/job/21217194464#step:4:136)

fix(Java): fix maven build

---

clients/go/test/api_uploads_test.go
openapi-generator/templates/go/README.mustache
openapi-generator/templates/go/go.mod.mustache

Bumping the major version for phrase-go unfortunately didn't work automatically

chore: fix go module version

---

clients/cli/build/release.sh

Adds a link to https://github.com/phrase/openapi/blob/master/clients/cli/CHANGELOG.md to the body of the release, so that the changelog can easily be found by users that are subscribed to new releases.
Docs: https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release
PR created as per request in https://github.com/phrase/phrase-cli/pull/146#discussion_r1599902539

ci(release.sh): add link to changelog to release body

---

doc/compiled.json
parameters.yaml
paths.yaml
paths/repo_syncs/activate.yaml
paths/repo_syncs/deactivate.yaml
paths/repo_syncs/events.yaml
paths/repo_syncs/export.yaml
paths/repo_syncs/import.yaml
paths/repo_syncs/show.yaml

The param to work with a resource should be called simply `id`

fix(CLI): use id instead of repo_sync_id as param

---

clients/go/.github/workflows/release.yml

Addresses https://github.com/phrase/phrase-go/actions/runs/9480403418/job/26120994452
https://goreleaser.com/deprecations/#-rm-dist

build(go): Update deprecated --rm-dist argument

---

doc/compiled.json
paths/releases/create.yaml
paths/releases/update.yaml

Add missing `app_min_version` and `app_max_version` params to the release endpoints

fix(API): add app_min_version and app_max_version param to releases

---

clients/cli/cmd/internal/pull.go

Addresses https://github.com/phrase/phrase-cli/issues/151 the bug that was introduced with the last async download feature

fix(CLI): Pull should not crash on empty files

---

clients/go/test/api_locales_test.go
openapi-generator/templates/go/api.mustache
openapi-generator/templates/go/client.mustache

Fix serializing format_options when downloading locales. We're using a nested structure for `custom_metadata_columns` which were being wrongfully sent as `{"custom_metadata_columns"=>"map[foo:5]"}`.
Similar to the issue we fixed for uploads in https://github.com/phrase/openapi/pull/498
https://phrase.atlassian.net/browse/TSI-2594

fix(go): Fix query param serialization of nested objects [TSI-2594]

---

clients/php/test/Api/LocalesApiTest.php
openapi-generator/templates/php/api.mustache

Fix query param serialization of nested fields such as `format_options` and `custom_metadata_filters` for locale download in PHP SDK. It seems Guzzle's query builder can't properly handle nested arrays, using the built-in `http_build_query` function seems to fix the issue.
https://phrase.atlassian.net/browse/TSI-2593

fix(PHP): Fix query param serialization of nested objects [TSI-2593]

---

.github/workflows/test-python.yml
clients/python/test/test_locales_api.py
clients/python/test/test_uploads_api.py
openapi-generator/templates/python/test-requirements.mustache

Introduce separate `pytest` version for Python versions newer than `3.7`, as it caused the build to fail. 
Also adjust the `test-python` workflow to use `pytest` as well for consistency.
**ℹ️ This will be merged after the issue with PyPI is resolved.**
https://phrase.atlassian.net/browse/TSI-2469

build(python): Adjust test dependencies for Python versions >= 3.7 [TSI-2469]

---

clients/java/src/test/java/com/phrase/client/api/UploadsApiTest.java
doc/compiled.json
paths/uploads/create.yaml

Add `update_translations_on_source_match` to update target translations only if the source translations match the uploaded multilingual file.

feat: Add update_translations_on_source_match

---

doc/compiled.json
paths/locale_downloads/create.yaml

- Related to https://phrase.atlassian.net/browse/TSS-3542
Required for orchestrator to pick up the new parameter

feat: Document locale_ids param

---

doc/compiled.json
paths/projects/create.yaml

Boolean params should not be quoted

chore(docs): Fix quoting of boolean param in CLI example

---

.github/workflows/test-cli.yml
Makefile

Run the CLI tests only when there are related changes, otherwise it fails due to missing Go package version.

build(CLI): Run test workflow only for CLI releases

---

doc/compiled.json
paths/jobs/remove_keys.yaml
paths/projects/create.yaml
paths/projects/update.yaml

- Remove smart_suggest params as the feature is no longer supported in editor
- Fix key_ids description for `remove_keys` endpoint

chore(docs): remove deprecated smart_suggest params

---

clients/java/src/test/java/com/phrase/client/api/UploadsApiTest.java
openapi-generator/templates/java/libraries/okhttp-gson/ApiClient.mustache

Java: nested parameters (e.g. `format_options` in "create upload" call) were not properly encoded when constructing multipart request.
https://phrase.atlassian.net/browse/STRINGS-411

fix(java): Properly encode nested parameters with file upload

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/test-cli.yml
.github/workflows/test-go.yml
.tool-versions

Requests are cached for 30 minutes when a non existing version is requested. This is causing lots of build failures during the time when a new phrase-go version is published and used. By setting `GOPRIVATE` the proxy should be skipped and the package directly fetched from GitHub

chore: disable golang proxy for phrase-go

---

clients/php/test/Api/UploadsApiTest.php
openapi-generator/templates/php/ObjectSerializer.mustache
openapi-generator/templates/php/api.mustache

Related to https://github.com/phrase/openapi/pull/130
This PR adds better support for serializing form parameters (e.g. when uploading file through API):
* passing in arrays and objects
* support nested structures

fix(PHP): Fix serializing nested form parameters #STRINGS-730

---

doc/compiled.json
paths/keys/create.yaml

Seems that this parameter was undocumented.
https://memsource.slack.com/archives/C02QV9K8EP5/p1731599023473799
- https://phrase.atlassian.net/browse/STRINGS-786

feat(API): autotranslate param in key creation [STRINGS-786]

---

clients/cli/cmd/internal/pull.go
clients/cli/cmd/internal/pull_target.go
clients/cli/cmd/internal/push.go
clients/cli/cmd/internal/push_source.go
clients/cli/cmd/internal/shared.go

Supports getting the branch from pull target configuration.
https://github.com/phrase/phrase-cli/issues/152

feat(CLI): Support branch in pull config #STRINGS-538

---

clients/cli/cmd/internal/pull.go
clients/cli/cmd/internal/pull_target.go

addresses https://github.com/phrase/phrase-cli/issues/157

fix(CLI): crash when target/params section is empty #STRINGS-921

---

doc/compiled.json
parameters.yaml
paths/job_comments/create.yaml
paths/job_comments/destroy.yaml
paths/job_comments/index.yaml
paths/job_comments/show.yaml
paths/job_comments/update.yaml
paths/job_locales/destroy.yaml
paths/job_locales/index.yaml
paths/job_locales/show.yaml

Also extract query branch parameter to parameters.yaml

fix(API): Add missing branch parameter to job comment endpoints #STRINGS-988

---

clients/cli/build/release.sh

Since the latest release cURL no longer seems to skip uploads of directories and raises an error instead.
Previous log output:
```
Uploading ./dist/linux
sha256sum: ./dist/linux: Is a directory
```
Latest cURL in the release image:
```
Uploading ./dist/linux
curl: option --data-binary: error encountered when reading a file
```

chore(cli): skip directories in CLI release

---

.tool-versions
doc/compiled.json
paths/repo_sync_events/index.yaml
paths/repo_sync_events/show.yaml
paths/repo_syncs/activate.yaml
paths/repo_syncs/deactivate.yaml
paths/repo_syncs/export.yaml
paths/repo_syncs/import.yaml
paths/repo_syncs/index.yaml
paths/repo_syncs/show.yaml
schemas/repo_sync_event.yaml

Hey @horstmannmat, I changed slightly your PR https://github.com/phrase/openapi/pull/747 by extracting "Repo Sync Events" to a separate section (IMO it's more RESTful that way and makes future extending of the events API a bit easier).
Would you mind telling me what you think, would that work for you?
cc @theSoenke

fix(API): Repo Sync schema fixes #STRINGS-1074

---

doc/compiled.json
main.yaml
schemas/repo_sync_event.yaml

unfortunately, it seems that `anyOf` is not handled properly by our client builders.
```
ERROR: json: cannot unmarshal string into Go struct field RepoSyncEvent.errors of type phrase.RepoSyncEventErrorsInner
```
so, I simplified this part of schema to always expect just an array of strings. We'll make sure that the server also always sends simple strings.

fix(API): Repo Sync Event errors field type #STRINGS-1074

---

doc/compiled.json
paths/jobs/remove_keys.yaml

Fix passing the `translation_key_ids` as arrays in query params are not properly supported by the generated client and move the param to the body. Also move the branch param to the request body to align it with keys_create`
https://github.com/phrase/phrase-cli/issues/158

fix(API): pass translation_key_ids when removing keys from job

---

clients/java/src/test/java/com/phrase/client/api/LocalesApiTest.java
doc/compiled.json
openapi-generator/templates/cli/api.handlebars
openapi-generator/templates/go/api.mustache
paths/locales/download.yaml

Allow `locale_ids` param in synchronous download endpoint.

feat(API): Add locale_ids param to synchronous download endpoint [STRINGS-1492]

---

doc/compiled.json
schemas/upload.yaml

Attribute `tags` of an Upload resource was previously undocumented. Also, added some description to show the difference between `tag` and `tags`. 
https://phrase.atlassian.net/browse/STRINGS-1221

feat(API): document tags attribute of an upload #STRINGS-1221

---

doc/compiled.json
parameters.yaml
paths/keys/destroy-collection.yaml
paths/keys/exclude.yaml
paths/keys/include.yaml
paths/keys/index.yaml
paths/keys/search.yaml
paths/keys/tag.yaml
paths/keys/untag.yaml

Document the feature which enables users to match keys by passing multiple upload IDs to `unmentioned_in_upload` search parameter. This will match only those keys not appearing in any of the uploads.

docs(API): unmentioned_in multiple uploads works too #STRINGS-1379

---

clients/cli/cmd/internal/push.go
clients/cli/cmd/internal/shared.go

As our backend now supports multiple upload ids when deleting unmentioned keys, this PR uses that feature to simplify cleanup and enable cleanup over multiple sources.
Addresses https://github.com/phrase/phrase-cli/issues/147

feat(CLI): Support cleanup over multiple sources #STRINGS-1378

---

clients/cli/cmd/internal/init.go

When running `phrase init`, we should not save the token to the configuration file by default, as that's not safe from security perspective (tokens should not be committed to the repository).
Instead, we ask the user explicitly if they want to save it, otherwise we don't.
Addresses https://github.com/phrase/phrase-cli/issues/18

feat(CLI): Do not save token to config file by default #STRINGS-999

---

.github/workflows/test-php.yml
clients/php/test/Api/KeysApiTest.php
clients/php/test/Api/LocalesApiTest.php
clients/php/test/Api/UploadsApiTest.php
openapi-generator/templates/php/api.mustache
openapi-generator/templates/php/api_test.mustache
openapi-generator/templates/php/composer.mustache
openapi-generator/templates/php/model_generic.mustache
openapi-generator/templates/php/model_test.mustache

PHP 8.4 deprecated some language features which results with some warnings, both from our code and some dependencies. This PR addresses this and bumps PHP, and phpunit and guzzlehttp libraries.
https://github.com/phrase/phrase-php/issues/4

feat(PHP): Address PHP 8.4 deprecations #STRINGS-1764

---

doc/compiled.json
schemas/upload.yaml

Add `processed_translations` and `upload_total_translations` to `upload.summary` schema
- https://phrase.atlassian.net/browse/STRINGS-1976

feat(API): Add processed & upload total translations on upload summary

---

.github/workflows/developer-hub.yml
.github/workflows/lawa.yml

This PR adds a GitHub Actions workflow that automatically notifies the `phrase/developer-hub` repository when changes are pushed to the main branch of `phrase/openapi`.
- The workflow triggers on every push to main.
- It uses `repository_dispatch` to send a custom event (`trigger-strings-workflow`) to the `phrase/developer-hub` repository.
- The payload includes context about the source repository and event type:
```
{
"source": "phrase/openapi",
"type": "update"
}
```
- The event is then listened here: https://github.com/phrase/developer-hub/pull/9
- [STRINGS-2428: Set up GH Actions to automate OpenAPI specs updates](https://phrase.atlassian.net/browse/STRINGS-2428)

chore(STRINGS-2428): Add workflow to automate Strings OpenAPI changes

---

.github/workflows/test-cli.yml
clients/cli/cmd/internal/init.go
clients/cli/cmd/internal/push_source.go

golang 1.24 introduces some more strict check on format strings sent to printf and alike. this doesn't block the build, but pops up when running the (currently empty) test suite.
This PR addresses these issues.

fix(CLI): address additional checks introduced by golang 1.24

---

doc/compiled.json
paths/locale_downloads/create.yaml
paths/locales/download.yaml

Make it clear updated the results included updated translations and keys

chore(docs): clarify updated_since description

---

doc/compiled.json
schemas/locale.yaml
schemas/translation.yaml
schemas/translation_key.yaml

`use_ordinal_rules` boolean is used to define whether is using ORDINAL or CARDINAL pluralization rules.
Add `ordinal_plural_forms` to locales endpoint.

feat(API): Add use_ordinal_rules boolean [STRINGS-2273]

---

doc/compiled.json
paths/keys/create.yaml
paths/keys/update.yaml
schemas/key_preview.yaml

- Add the `use_ordinal_rules` attribute to create/update keys endpoint request bodies as it was implemented and should be to the documentation.
- Add use_ordinal_rules to key_preview object
Follow-up on PR: https://github.com/phrase/openapi/pull/846

feat(API): Add use_ordinal_rules attribute to request body for create/update Keys endpoints

---

openapi-generator/templates/typescript-fetch/package.mustache

Fix TS test suite (broken since https://github.com/phrase/openapi/pull/872) by bumping the TS version.

build(typescript): bump dev TS version to 5.9

---

README.md

This repo only contains documentation for Phrase Strings.

chore(docs): README title clarification
