phrase/openapi

doc/compiled.json
main.yaml
openapi-generator/cli_lang.yaml
openapi-generator/java_lang.yaml
openapi-generator/php_lang.yaml
openapi-generator/python_lang.yaml
openapi-generator/ruby_lang.yaml
openapi-generator/typescript_lang.yaml
parameters.yaml
paths.yaml
paths/teams/add_project.yaml
paths/teams/add_space.yaml
paths/teams/add_user.yaml
paths/teams/create.yaml
paths/teams/delete.yaml
paths/teams/index.yaml
paths/teams/remove_project.yaml
paths/teams/remove_space.yaml
paths/teams/remove_user.yaml
paths/teams/show.yaml
paths/teams/update.yaml
schemas.yaml
schemas/team.yaml
schemas/team_detail.yaml

hope i was able to add everything correctly

add team docs

---

doc/compiled.json
paths/projects/create.yaml

migrating pr from openapi https://github.com/phrase/apidocs/pull/109

add clone project

---

openapi-generator/templates/typescript-fetch/apis.mustache

https://trello.com/c/wbhBlvS0/765-improve-js-client

JS: use any for unknown return type

---

doc/index.html

references issue https://phraseapp.atlassian.net/browse/INTEGRATE-40?atlOrigin=eyJpIjoiOTMwNzFiMDE2MDE0NGI3ZGIzMWU2YzFjOTYxZDVkN2YiLCJwIjoiaiJ9

docs: page optimization - defer GTM load

---

paths/jobs/create.yaml
paths/jobs/update.yaml
schemas/job.yaml

Introduced recently, add support for ticket_url field in jobs.

Jobs: Add ticket_url field

---

paths.yaml
paths/jobs/index_account.yaml

Support the new endpoint to fetch all jobs for an account.

Add documentation for jobs by account endpoint

---

openapi-generator/templates/cli/README.handlebars
openapi-generator/templates/cli/README.mustache

add README for docker usage

---

paths/screenshots/index.yaml

API allows to filter for key_id when listing screenshots.

Screenshots: Add key_id filter

---

openapi-generator/php_lang.yaml
openapi-generator/templates/php/.gitattributes

Generate more clean archive files

Add .gitattributes file for phrase-php

---

openapi-generator/templates/cli/README.mustache

Fix documentation links from old help center

Fix CLI readme links

---

openapi-generator/templates/cli/api.handlebars

https://phraseapp.atlassian.net/browse/INTEGRATE-578

display api result if there was an error

---

openapi-generator/go_lang.yaml
paths/locales/download.yaml

Not sure if that is how it works. Therefore I opened a draft to have a discussion with @theSoenke

add exclude empty zero forms

---

schemas/branch_name.yaml
schemas/job.yaml

Jobs now also return branch information if available.

Jobs: Now include branch information as well

---

openapi-generator/cli_lang.yaml
openapi-generator/templates/cli/go.mod.mustache

Trying to update CLI (minor change)

adjust go version, package version for cli

---

clients/cli/go.mod
clients/cli/go.sum

Update to correct latest phrase-go version

CLI: Update to latest phrase-go

---

schemas/job_locale.yaml

Useful to determine which locales are completed.

Jobs: Expose "completed" state for job locales

---

paths/members/update.yaml
schemas/member.yaml

Purpose:
Allow default_locale_codes parameter in member#update API as we have it in our frontend already.
Related changes:
https://github.com/phrase/phrase/pull/7300

Api default locale codes WORKFLOWS-415

---

openapi-generator/go_lang.yaml

There is nothing new in this version, but I want to test the auto-release pipeline.

release phrase-go 1.0.15

---

paths/members/destroy.yaml
paths/members/index.yaml
paths/members/show.yaml
paths/members/update.yaml
responses.yaml
schemas/member.yaml

Updated documentation by adding space_ids param to member#update API
https://github.com/phrase/phrase/pull/7307

Add space_ids param to member#update API WORKFLOWS-417

---

clients/cli/build/release.sh
clients/cli/build/update_brew.sh

The plan:
1. Clone `homebrew-brewed` to a tmp folder.
2. Replace file hashes and version in `phrase.rb`.
3. push to master

autorelease brew

---

openapi-generator/cli_lang.yaml

https://github.com/phrase/openapi/pull/66

Bump cli version

---

openapi-generator/ruby_lang.yaml

https://github.com/phrase/openapi/pull/66

Bump Ruby to 1.0.11

---

paths.yaml
paths/variables/create.yaml
paths/variables/destroy.yaml
paths/variables/index.yaml
paths/variables/show.yaml
paths/variables/update.yaml
schemas/variable.yaml

Introducing the new Variables API to allow managing variables per project.

Add variables API

---

paths/users/user.yaml
schemas.yaml
schemas/current_user.yaml
schemas/user.yaml

https://phraseapp.atlassian.net/browse/WORKFLOWS-755 
https://github.com/phrase/phrase/pull/7497

Added language to current user WORKFLOWS-755

---

clients/cli/go.mod
clients/cli/go.sum
openapi-generator/cli_lang.yaml

update to current go lib version to support batch actions

update client to support batch actions

---

clients/cli/build/build.sh
clients/cli/build/update_brew.sh
openapi-generator/cli_lang.yaml

- Create tar file of M1 binary for homebrew

CLI: Add tar file for M1 brew package

---

schemas/job_locale.yaml

Needed for the editor https://phraseapp.atlassian.net/browse/WORKFLOWS-1126
https://github.com/phrase/phrase/pull/7630

Include translation/review completed_at in JobLocale [WORKFLOWS-1126]

---

clients/cli/cmd/internal/pull.go
openapi-generator/cli_lang.yaml
openapi-generator/templates/cli/api.handlebars

This is a collection of fixes for generating the phrase-cli that should probably be merged in one single PR.

Go CLI fixes

---

paths/projects/index.yaml
schemas/project.yaml
schemas/space_short.yaml
schemas/team.yaml
schemas/team_detail.yaml

doc part for https://github.com/phrase/phrase/pull/7692

Add sort_by param to projects#index [WORKFLOWS-1193]

---

clients/cli/build/innosetup/postinstall.rtf
openapi-generator/cli_lang.yaml

CLI: Fix links in the installer

---

parameters.yaml
paths/projects/index.yaml

Add account id filter in query part of url (projects#index)
https://phraseapp.atlassian.net/browse/WORKFLOWS-1284

Filter projects by account id

---

openapi-generator/go_lang.yaml

Create a new release to add the new `SortBy` param https://github.com/phrase/openapi/pull/92/

phrase-go: Update to 2.0.1

---

clients/cli/cmd/internal/upload_cleanup.go
clients/cli/cmd/upload_cleanup.go
clients/cli/go.mod
clients/cli/go.sum
openapi-generator/cli_lang.yaml

Add branch param to make upload cleanup work with branches. Fix https://github.com/phrase/phrase-cli/issues/71

CLI: Add branch param to upload cleanup command

---

clients/cli/build/release.sh
clients/java/.github/workflows/release.sh
clients/kotlin/.github/workflows/release.sh
clients/ruby/.github/workflows/release.sh

Python version has changed from 2 to 3 https://github.com/phrase/phrase-cli/runs/2138254761

Support Python 3 in release scripts

---

schemas/account.yaml

- https://phraseapp.atlassian.net/browse/WORKFLOWS-1291

Add company_logo_url to account [WORKFLOWS-1291]

---

openapi-generator/php_lang.yaml
openapi-generator/templates/php/composer.mustache

Implement changes from https://github.com/phrase/phrase-php/pull/2

Update guzzle to 7.3

---

paths/locales/index.yaml

Added documentation for sort_by in locales
https://phraseapp.atlassian.net/browse/WORKFLOWS-1443
https://github.com/phrase/phrase/pull/7869

WORKFLOWS-1443: Added documentation for sort_by in locales

---

openapi-generator/typescript_lang.yaml
paths/projects/create.yaml
schemas/branch.yaml

Added options to create project
Added response documentation to branches

Add supported parameters to projects/create and branch

---

schemas/account.yaml
schemas/subscription.yaml

apidocs part of https://github.com/phrase/phrase/pull/7953
https://phraseapp.atlassian.net/browse/WORKFLOWS-1556

Add subscription to account [WORKFLOWS-1556]

---

doc/compiled.json
paths.yaml
paths/notification_groups/index.yaml
paths/notifications/index.yaml
schemas/account.yaml
schemas/account_details.yaml
schemas/notification.yaml
schemas/notification_group.yaml
schemas/notification_group_detail.yaml
schemas/user.yaml
schemas/user_preview.yaml

- Adds index action documentation for Notifcations
- Adds index action documentation for Notification Groups

Add Notification and Notification Groups index documentation

---

paths.yaml
paths/notification_groups/mark_all_as_read.yaml
paths/notification_groups/mark_as_read.yaml
paths/notifications/mark_all_as_read.yaml
paths/notifications/show.yaml

- Adds `notifications/:id` action
- Adds `notifications/mark_all_as_read` action
- Adds `notifcation_groups/:id/mark_as_read` action
- Adds `notifcation_groups/mark_all_as_read` action

Update docs to include all notification/notification group actions

---

schemas/comment.yaml

https://phraseapp.atlassian.net/browse/WORKFLOWS-1634
https://github.com/phrase/phrase/pull/8005
https://github.com/phrase/phrase_graphql/pull/183
https://github.com/phrase/phrase-vue/pull/681

feat(WORKFLOWS-1634): Added mentioned users to comments

---

paths/orders/create.yaml
schemas/translation_order.yaml

Adding the name field to orders in the docs
it is not a required field since it always get set before saved(before validations even)
https://github.com/phrase/phrase/pull/8015
https://phraseapp.atlassian.net/browse/WORKFLOWS-1741

add name field to orders with example for create

---

schemas/notification_group_detail.yaml

api docs adjustment for https://github.com/phrase/phrase/pull/8025

notification count on notifications group [WORKFLOWS-1747]

---

clients/cli/cmd/internal/push.go
clients/cli/go.mod
clients/cli/go.sum
openapi-generator/cli_lang.yaml

[INTEGRATE-1147] globbing works with windows

---

paths.yaml
paths/keys/exclude.yaml
paths/keys/include.yaml

Two new endpoints to allow batch excluding and including locales on keys.

Keys: Batch Exclude/Include in locale

---

paths.yaml
paths/accounts/search.yaml
paths/search/in_account.yaml
schemas/account_search_result.yaml

Updates documentation to include search across projects.

Add documentation for account-level search

---

paths/members/update.yaml

- A new "strategy" parameter was added to the members#update endpoint.
- Providing this parameter will result in either setting, adding or removing given spaces, projects and/or locales on users access list

Member: Introduce update strategy

---

paths/projects/index.yaml

Update docs
https://github.com/phrase/phrase/pull/8120

feat(WORKFLOWS-1842): Add filtering by favorite to project#index

---

paths/projects/index.yaml

Add item type to array to fix master

Add item type to array

---

openapi-generator/go_lang.yaml
openapi-generator/java_lang.yaml
openapi-generator/php_lang.yaml
openapi-generator/python_lang.yaml
openapi-generator/ruby_lang.yaml
openapi-generator/typescript_lang.yaml

Prepare release with a template jobs endpoint for languages:
- go
- php
- js
- python
- java
- ruby

INTEGRATE-1272: bump release versions

---

clients/java/.github/workflows/release.sh

Java Release is failing on pushing to github.

Rename Java release build

---

openapi-generator/go_lang.yaml

Required for a new CLI release

Release phrase-go 2.1.1

---

clients/cli/cmd/internal/updatechecker/update_checker.go
clients/cli/go.mod
clients/cli/go.sum
openapi-generator/cli_lang.yaml

Fix issue when the cached version state can not be written and use 666 for file permissions
https://github.com/phrase/phrase-cli/issues/86

Fix cache file permissions

---

clients/cli/cmd/internal/push.go
clients/cli/cmd/internal/push_source.go
clients/cli/cmd/push.go

Suggestion PR, to tag uploaded keys with the phrase push
https://github.com/phrase/phrase-cli/pull/74

Pre select the Tag for the uploaded keys

---

openapi-generator/cli_lang.yaml

Release new CLI to include tag option for pushing translations https://github.com/phrase/openapi/pull/143

Update CLI to 2.3.0

---

paths/invitations/create.yaml
paths/invitations/update.yaml

Purpose: allow team assignment on invitation#create/update

Add team_ids param to invitation create & update [WORKFLOWS-1798]

---

paths/icu/skeleton.yaml

- https://github.com/phrase/phrase/pull/8597
- https://memsourcegroup.atlassian.net/browse/WORKFLOWS-2561

Add icu skeleton endpoint to OpenAPI [WORKFLOWS-2561]

---

paths.yaml
paths/icu/skeleton.yaml
schemas.yaml
schemas/icu.yaml

- Add icu to navigation
- Add example response of icu skeleton

Fix icu skeleton (add to navigation)

---

doc/compiled.json
main.yaml

Preparation to bunch of API Docs improvements:
- Sort Operations in the menu alphabetically for better user experience

:children_crossing: Sort Operations alphabetically

---

clients/cli/go.mod
clients/cli/go.sum
openapi-generator/cli_lang.yaml

Release fix from https://github.com/phrase/openapi/pull/154

Update phrase-cli to 2.4.1

---

README.md
doc/compiled.json
package-lock.json
schemas/project.yaml
schemas/user_preview.yaml

Add new field point_of_contact to project information

Add point of contact to project

---

schemas/member.yaml
schemas/team_short.yaml

Add new fields to member and team_short

[TSS-89] add teams_short to members

---

doc/compiled.json
schemas/invitation.yaml

Include teams data in invitations

Include teams data in invitations

---

schemas/project_locales.yaml
schemas/project_member_specific.yaml

https://memsourcegroup.atlassian.net/jira/software/c/projects/TSS/boards/17?modal=detail&selectedIssue=TSS-92

[TSS-92] Add project role to projects within memberships

---

doc/compiled.json
main.yaml
openapi-generator/ruby_lang.yaml

phrase-ruby contains an issue triggered by JWT auth which is overwriting headers set by token auth. JWT tokens are also no publicly usable yet

Remove JWT auth method

---

paths/jobs/lock_job.yaml
paths/jobs/unlock_job.yaml

[INTEGRATE-1429](https://memsourcegroup.atlassian.net/browse/INTEGRATE-1429)

INTEGRATE-1429: Add `lock` and `unlock` endpoint definitions to OpenAPI

---

paths/icu/skeleton.yaml

Document new `keep_content` parameter

Document keep_content param

---

openapi-generator/go_lang.yaml
openapi-generator/java_lang.yaml
openapi-generator/php_lang.yaml
openapi-generator/python_lang.yaml
openapi-generator/ruby_lang.yaml
openapi-generator/typescript_lang.yaml

Release a new version of the libraries to include the latest API changes

Release new libraries

---

clients/cli/.github/workflows/issue_commented.yml
clients/cli/.github/workflows/issue_created.yml

Remove Zendesk GitHub action

---

clients/cli/cmd/internal/init.go
clients/cli/cmd/internal/shared.go

Show all projects in the init step

Add pagination for projects

---

doc/compiled.json
main.yaml
paths/blacklisted_keys/create.yaml
paths/blacklisted_keys/destroy.yaml
paths/blacklisted_keys/index.yaml
paths/blacklisted_keys/show.yaml
paths/blacklisted_keys/update.yaml
paths/glossaries/create.yaml
paths/glossaries/destroy.yaml
paths/glossaries/index.yaml
paths/glossaries/show.yaml
paths/glossaries/update.yaml
paths/glossary_term_translations/create.yaml
paths/glossary_term_translations/destroy.yaml
paths/glossary_term_translations/update.yaml
paths/glossary_terms/create.yaml
paths/glossary_terms/destroy.yaml
paths/glossary_terms/index.yaml
paths/glossary_terms/show.yaml
paths/glossary_terms/update.yaml
paths/versions/index.yaml

Update localization
- https://memsource.tpondemand.com/entity/68141-strings-api-documentation-update-localization-files

chore(#68141): Update localization

---

clients/cli/cmd/internal/pull.go
openapi-generator/cli_lang.yaml

https://github.com/phrase/phrase-cli/issues/93

Update locale download permissions

---

doc/compiled.json
main.yaml
paths/blacklisted_keys/create.yaml
paths/blacklisted_keys/destroy.yaml
paths/blacklisted_keys/index.yaml
paths/blacklisted_keys/show.yaml
paths/blacklisted_keys/update.yaml
paths/glossaries/create.yaml
paths/glossaries/destroy.yaml
paths/glossaries/index.yaml
paths/glossaries/show.yaml
paths/glossaries/update.yaml
paths/glossary_term_translations/create.yaml
paths/glossary_term_translations/destroy.yaml
paths/glossary_term_translations/update.yaml
paths/glossary_terms/create.yaml
paths/glossary_terms/destroy.yaml
paths/glossary_terms/index.yaml
paths/glossary_terms/show.yaml
paths/glossary_terms/update.yaml
paths/versions/index.yaml
paths/versions/show.yaml

Reverts phrase/openapi#193 phrase/openapi#192
Currently the whole Libs and builds are broken.

Revert "Add missing localization changes"

---

clients/cli/cmd/internal/shared.go
openapi-generator/cli_lang.yaml

In the error case the http_response can be nil

fix seg fault https://github.com/phrase/phrase-cli/issues/99

---

doc/compiled.json
paths/distributions/create.yaml
paths/distributions/update.yaml
paths/glossary_terms/create.yaml
paths/glossary_terms/update.yaml
paths/projects/create.yaml
paths/projects/update.yaml

Remove quotes around boolean values in examples and simplify the project create and update example

Fix quotes for boolean params in examples

---

openapi-generator/cli_lang.yaml
openapi-generator/templates/cli/api.handlebars

Fix handling of non primitiv and non model params like filter on projects list endpoint.

fix cli client Error: unexpected end of JSON input and release 2.4.10

---

clients/cli/.github/workflows/issue_commented.yml
clients/cli/.github/workflows/issue_created.yml
clients/go/.github/workflows/issue_commented.yml
clients/go/.github/workflows/issue_created.yml
clients/java/.github/workflows/issue_commented.yml
clients/java/.github/workflows/issue_created.yml
clients/php/.github/workflows/issue_commented.yml
clients/php/.github/workflows/issue_created.yml
clients/python/.github/workflows/issue_commented.yml
clients/python/.github/workflows/issue_created.yml
clients/ruby/.github/workflows/issue_commented.yml
clients/ruby/.github/workflows/issue_created.yml
clients/typescript/.github/workflows/issue_commented.yml
clients/typescript/.github/workflows/issue_created.yml

Proxy issues through support team via zendesk in client public repos.
PS: I haven't changed anything for kotlin since we are going to remove kotlin from the repo

Add zendesk integration to clients

---

doc/compiled.json
openapi-generator/go_lang.yaml
openapi-generator/java_lang.yaml
openapi-generator/php_lang.yaml
openapi-generator/python_lang.yaml
openapi-generator/ruby_lang.yaml
openapi-generator/typescript_lang.yaml
paths/distributions/create.yaml
paths/distributions/update.yaml
paths/locales/create.yaml
paths/locales/update.yaml
schemas/locale.yaml

https://memsource.tpondemand.com/entity/73263-api-allow-fallback_locale_id-parameter-in-localecreate

Add support for fallback locale to locales#create and locales#update

---

clients/cli/go.mod
clients/cli/go.sum
openapi-generator/cli_lang.yaml

- Add support for fallback locales

Release new client version 2.4.12

---

clients/cli/build/release.sh

Add latest tagged release for better consumer QOL :)
https://github.com/phrase/phrase-cli/issues/88

Add latest docker release for Phrase CLI

---

intro.md
openapi-generator/templates/go/README.mustache
openapi-generator/templates/go/configuration.mustache
openapi-generator/templates/java/api_doc.mustache
openapi-generator/templates/java/libraries/okhttp-gson/README.mustache
openapi-generator/templates/php/README.mustache
openapi-generator/templates/python/common_README.mustache
openapi-generator/templates/ruby-client/README.mustache
openapi-generator/templates/shared/datacenters.mustache
openapi-generator/templates/typescript-fetch/README.mustache

Update client readmes with US DC host

Update client Readmes with US Datacenter How-To

---

openapi-generator/java_lang.yaml
openapi-generator/php_lang.yaml
openapi-generator/python_lang.yaml
openapi-generator/ruby_lang.yaml
openapi-generator/typescript_lang.yaml

Release new version of libraries

---

openapi-generator/php_lang.yaml

Prepare new release of the PHP library

Update phrase-php to 1.5.2

---

doc/compiled.json
openapi-generator/go_lang.yaml
openapi-generator/java_lang.yaml
openapi-generator/php_lang.yaml
openapi-generator/python_lang.yaml
openapi-generator/ruby_lang.yaml
openapi-generator/typescript_lang.yaml
paths.yaml

Fixes https://github.com/phrase/phrase-js/issues/12

Fix account locales parameter placeholder name

---

openapi-generator/templates/python/api_client.mustache
openapi-generator/templates/python/rest.mustache

Addresses https://github.com/phrase/phrase-python/issues/5

[Python] Use correct encoding when writing files

---

clients/cli/cmd/internal/print/print.go
clients/cli/cmd/internal/push.go
clients/cli/cmd/internal/shared/batch_mode.go
clients/cli/cmd/internal/spinner/spinner.go
clients/cli/cmd/internal/upload_cleanup.go
clients/cli/cmd/root.go
clients/cli/cmd/upload_cleanup.go

https://memsource.tpondemand.com/entity/74406-orch-support-option-in-phrase-cli

Introduce --batch option for CLI

---

paths/keys/search.yaml

[Modify tagged keys search](https://memsource.tpondemand.com/entity/80831-search-tags-rewrite-remaining-tag-search)

Modify docs to add limitation of tagged keys search

---

openapi-generator/cli_lang.yaml

Create a new release to include the tar file for Linux ARM

Update CLI to 2.6.1

---

doc/compiled.json
main.yaml
paths/locales/download.yaml
paths/projects/create.yaml
paths/projects/update.yaml

Use new links for formats documentation

Update links to formats documentation

---

clients/cli/cmd/internal/pull.go

Addresses https://github.com/phrase/phrase-cli/issues/105
Also eliminates multiple identical API calls when multiple tags are requested

CLI: pull should separate tags by files

---

openapi-generator/cli_lang.yaml

I believe this, as a bugfix, should be a patch release, but not 100% sure.

CLI version 2.6.2

---

clients/cli/Dockerfile
clients/cli/build/release.sh

Support ARM64 builds of the Docker image

Add platform linux/arm64 to Docker

---

doc/compiled.json
openapi-generator/go_lang.yaml
openapi-generator/java_lang.yaml
openapi-generator/php_lang.yaml
openapi-generator/python_lang.yaml
openapi-generator/ruby_lang.yaml
openapi-generator/typescript_lang.yaml
parameters.yaml
paths/locales/download.yaml
paths/translations/index.yaml

Addresses https://github.com/phrase/phrase-go/issues/7

Add conditional caching headers

---

clients/cli/.github/workflows/release.yml

Curly brackets are not needed here

Fix setting version output for CLI release

---

clients/cli/.github/workflows/release.yml

Open brew update PR on release

CLI: Automatically update brew formula

---

doc/compiled.json
paths/releases/create.yaml

The example in the docs was wrong and could not be correctly parsed by the CLI

Docs: Fix CLI release create example

---

clients/cli/.github/workflows/issue_commented.yml
clients/cli/.github/workflows/issue_created.yml
clients/cli/.github/workflows/zendesk_comment.yml
clients/cli/.github/workflows/zendesk_solve.yml
clients/go/.github/workflows/issue_commented.yml
clients/go/.github/workflows/issue_created.yml
clients/go/.github/workflows/zendesk_comment.yml
clients/go/.github/workflows/zendesk_solve.yml
clients/java/.github/workflows/issue_commented.yml
clients/java/.github/workflows/issue_created.yml
clients/java/.github/workflows/zendesk_comment.yml
clients/java/.github/workflows/zendesk_solve.yml
clients/php/.github/workflows/issue_commented.yml
clients/php/.github/workflows/issue_created.yml
clients/php/.github/workflows/zendesk_comment.yml
clients/php/.github/workflows/zendesk_solve.yml
clients/python/.github/workflows/issue_commented.yml
clients/python/.github/workflows/issue_created.yml
clients/python/.github/workflows/zendesk_comment.yml
clients/python/.github/workflows/zendesk_solve.yml
clients/ruby/.github/workflows/issue_commented.yml
clients/ruby/.github/workflows/issue_created.yml
clients/ruby/.github/workflows/zendesk_comment.yml
clients/ruby/.github/workflows/zendesk_solve.yml

Disable Zendesk integration

---

clients/cli/go.mod
clients/cli/go.sum
openapi-generator/cli_lang.yaml

Bump CLI to 2.6.6

---

Makefile

Fix running local docs server

---

doc/compiled.json
schemas.yaml

Follow up for https://github.com/phrase/openapi/pull/277

Fix items references for translator and reviewer teams

---

openapi-generator/go_lang.yaml

Release a new phrase-go version

Bump phrase-go to 2.6.8

---

openapi-generator/python_lang.yaml
openapi-generator/typescript_lang.yaml

Update versions to fix job team assignment params

Bump JS and Python library

---

.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/lint.yml
Makefile
lint.sh

- Fail on validation errors from `npx openapi-generator-cli validate`
- Check if the go and cli code is compiling
- Check `compiled.json` is up to date

Improve linting and check for compile errors

---

clients/cli/.github/workflows/vulnerabilities.yml
clients/typescript/.github/workflows/issue_commented.yml
clients/typescript/.github/workflows/issue_created.yml
clients/typescript/.github/workflows/zendesk_comment.yml
clients/typescript/.github/workflows/zendesk_solve.yml

- Sent vulnerability alerts to integrations channel
- Remove leftover Zendesk notifications

Change vulnerability alert channel

---

doc/compiled.json
main.yaml
openapi-generator/go_lang.yaml
openapi-generator/java_lang.yaml
openapi-generator/php_lang.yaml
openapi-generator/python_lang.yaml
openapi-generator/ruby_lang.yaml
openapi-generator/typescript_lang.yaml
paths.yaml
paths/organization_job_template_locales/create.yaml
paths/organization_job_template_locales/destroy.yaml
paths/organization_job_template_locales/index.yaml
paths/organization_job_template_locales/show.yaml
paths/organization_job_template_locales/update.yaml
paths/organization_job_templates/create.yaml
paths/organization_job_templates/destroy.yaml
paths/organization_job_templates/index.yaml
paths/organization_job_templates/show.yaml
paths/organization_job_templates/update.yaml
schemas.yaml
schemas/organization_job_template.yaml
schemas/organization_job_template_details.yaml

🚧 Do not merge until **March 1st**
Ticket: https://memsource.tpondemand.com/entity/87009-gjt-document-job-templates-and-locale

Document GJT endpoints

---

clients/cli/go.mod
clients/cli/go.sum
openapi-generator/cli_lang.yaml

Prepare new release to support OTA tags

CLI: Release 2.8.0

---

doc/compiled.json
openapi-generator/go_lang.yaml
openapi-generator/java_lang.yaml
openapi-generator/php_lang.yaml
openapi-generator/python_lang.yaml
openapi-generator/ruby_lang.yaml
openapi-generator/typescript_lang.yaml
paths.yaml
paths/job_locales/show.yaml

The path was pointing to the non-existing endpoint
https://memsourcegroup.atlassian.net/browse/TSI-1777

Fix URL for job locales endpoint #TSI-1777

---

doc/compiled.json

Completes https://github.com/phrase/openapi/pull/348

fix: Endpoint description change to avoid ambiguity

---

clients/java/.github/workflows/release.yml
openapi-generator/templates/java/libraries/okhttp-gson/build.gradle.mustache

following https://gist.github.com/sualeh/ae78dc16123899d7942bc38baba5203c

fix(java): Use useGpgCmd instead of in memory key

---

openapi-generator/templates/cli/README.handlebars

Provide an example how to use the Docker image to push and pull locales

docs: document Docker usage for mounting files

---

doc/compiled.json
schemas/gitlab_sync_history.yaml

fixes #362 
Signed-off-by: Matheus Horstmann

fix(schemas): Fix gitlab_sync type mismatch

---

doc/compiled.json
paths/jobs/create.yaml

Tags, and translation_key_ids need to be an array

docs: fix create jobs cli example

---

doc/compiled.json
main.yaml
parameters.yaml
paths.yaml
paths/comment_reactions/create.yaml
paths/comment_reactions/destroy.yaml
paths/comment_reactions/index.yaml
paths/comment_reactions/show.yaml
schemas.yaml
schemas/comment_reaction.yaml

https://github.com/phrase/phrase/pull/11577
https://memsourcegroup.atlassian.net/browse/TSE-950

feat(TSE-950): Document comment_reactions endpoints

---

doc/compiled.json
main.yaml
paths.yaml
paths/comment_reactions/create.yaml
paths/comment_replies/create.yaml
paths/comment_replies/destroy.yaml
paths/comment_replies/index.yaml
paths/comment_replies/mark_as_read.yaml
paths/comment_replies/mark_as_unread.yaml
paths/comment_replies/show.yaml
paths/comments/create.yaml
schemas/comment.yaml

- Added comment replies endpoint docs
- Adjusted comment #create to include locale_ids
- Adjusted reaction #create to include example
https://github.com/phrase/phrase/pull/11643
https://memsourcegroup.atlassian.net/browse/TSE-869

feat(API): Introduce comment replies endpoints

---

Makefile
doc/_variables.scss
doc/index.html
doc/main.scss
doc/rapidoc.scss

Use font from the internal CDN and switch to Inter font

chore(docs): Use Phrase font CDN

---

doc/compiled.json
paths/distributions/create.yaml

docs: Add rails as a supported platform

---

doc/compiled.json
paths/gitlab_syncs/destroy.yaml
paths/gitlab_syncs/export.yaml
paths/gitlab_syncs/import.yaml
paths/gitlab_syncs/index.yaml
paths/gitlab_syncs/show.yaml
paths/gitlab_syncs/update.yaml

Fix invalid GitLab Sync commands https://github.com/phrase/phrase-cli/issues/127

docs: fix gitlab cli commands

---

doc/compiled.json
main.yaml
parameters.yaml
paths.yaml
paths/reports/index.yaml
paths/reports/locales/index.yaml
paths/reports/show.yaml
schemas.yaml
schemas/locale_report.yaml
schemas/project_report.yaml

Documentation for https://github.com/phrase/phrase/pull/12135
- https://phrase.atlassian.net/browse/TSS-2439

feat: Add reports locales endpoint to API [TSS-2439]

---

clients/cli/cmd/internal/push.go

Output a convenient direct URL to the created upload upon push.

feat(CLI): On push, print upload URL [TSI-1735]

---

clients/cli/.github/workflows/release.yml

Try fixing https://github.com/phrase/phrase-cli/actions/runs/7197822807/job/19606050138

build(CLI): Update homebrew-bump-formula github action

---

.github/workflows/build.yml
clients/java/.github/workflows/release.yml
clients/php/.github/workflows/release.yml
clients/typescript/.github/workflows/release.yml

- Automatically push tags to publish releases for PHP, JS
- Create GitHub releases for php, js and java

chore: automate releasing for PHP and Java

---

openapi-generator/templates/java/libraries/okhttp-gson/pom.mustache

Addresses https://github.com/phrase/phrase-java/actions/runs/7207299256/job/19633880637

build(java): Add test dependency to pom.xml

---

openapi-generator/templates/go/client.mustache

This PR attempts to trigger release for CLI with Go.
fix(CLI): retrigger release for CLI
feat(GO): retrigger release for GO

feat: Retrigger release for CLI & GO

---

openapi-generator/templates/go/client.mustache

feat: Revert Retrigger release for CLI & GO

---

doc/compiled.json
paths.yaml
paths/quality_performance_score/index.yaml
responses.yaml
schemas/quality_performance_score.yaml

https://github.com/phrase/phrase/pull/12451
https://phrase.atlassian.net/browse/TSE-1334

feat(api): Add QPS endpoint and documentation

---

.gitignore
.tool-versions
clients/cli/go.sum
doc/compiled.json
paths.yaml
paths/quality_performance_score/index.yaml
schemas/quality_performance_score.yaml

- Adjust documentation of QPS endpoint
- Bump `.tool-versions` nodejs to LTS 20

fix(API): Adjust documentation of QPS endpoint

---

openapi-generator/templates/cli/README.handlebars

Addresses https://github.com/phrase/phrase-cli/issues/140

docs(CLI): More accurate HC links in CLI README

---

doc/index.html

Add cookiepro banner to apidocs

chore(docs): Add cookiepro banner

---

clients/cli/go.sum
doc/compiled.json
schemas/translation_details.yaml
schemas/translation_parent.yaml

Add "linked_parent" to translation-details.
https://phrase.atlassian.net/browse/TSS-3171

feat: Add linked-parent to translation details

---

clients/go/test/api_custom_metadata_test.go
clients/go/test/api_jobs_test.go
clients/go/test/api_locales_test.go
openapi-generator/templates/go/README.mustache
openapi-generator/templates/go/go.mod.mustache
release-please/config-go.json

Remove missed references to v2

fix(go): remove unused dependencies

---

openapi-generator/templates/go/README.mustache
openapi-generator/templates/go/go.mod.mustache

Update readme to list phrase-go v3 https://github.com/phrase/phrase-go/pull/11

chore: install latest phrase-go with go get

---

doc/compiled.json
schemas/locale_report.yaml

[TSS-3350] - Change percentages from Integer to Number to better reflect actual fractions.
[TSS-3350]: https://phrase.atlassian.net/browse/TSS-3350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Change reports percentage from Integer to Number

---

doc/compiled.json
main.yaml
paths.yaml
paths/release_triggers/create.yaml
paths/release_triggers/destroy.yaml
paths/release_triggers/index.yaml
paths/release_triggers/show.yaml
paths/release_triggers/update.yaml
schemas.yaml
schemas/release_trigger.yaml

https://github.com/phrase/phrase/pull/13499

feat(API): Add OTA Release Triggers API [TSI-2485]

---

doc/compiled.json
main.yaml
paths.yaml
paths/locale_downloads/create.yaml
paths/locale_downloads/show.yaml
schemas.yaml
schemas/locale_download.yaml

Exposing asynchronous locale downloads endpoint

feat(API): Async downloads [TSI-2515]

---

openapi-generator/templates/ruby-client/gemspec.mustache

Addresses https://github.com/phrase/phrase-ruby/pull/10

feat(ruby): Remove dependency version constraints

---

.github/workflows/test-java.yml
clients/java/.license-decisions.yml

Added two explicit approvals, according to https://phrase.atlassian.net/wiki/spaces/ENG/pages/3729064011/Open+Source+Software+Policy both libraries are "Copyleft -- Static & Dynamic".

build(java): Add license check [TSI-2538]

---

.github/workflows/test-php.yml
clients/php/.license-decisions.yml

https://phrase.atlassian.net/browse/TSI-2630

build(php): Add license check [TSI-2630]

---

.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/test-cli.yml
.github/workflows/test-go.yml
.github/workflows/test-php.yml
.github/workflows/test-ruby.yml
.github/workflows/test-typescript.yml
clients/cli/.github/workflows/release.yml

Fix GitHub action deprecation warnings

chore: Update deprecated GitHub actions

---

clients/cli/cmd/internal/init.go
clients/cli/cmd/internal/push.go
clients/cli/go.sum

A change in formats API caused CLI build to break. This PR fixes it.

fix(cli): Adapt to formats API fix

---

doc/compiled.json
paths/keys/search.yaml
paths/search/in_account.yaml
paths/translations/search.yaml

https://phrase.atlassian.net/browse/STRINGS-457
https://github.com/phrase/phrase/pull/14180

feat(API): Add Pagination header to POST search endpoints [#457]

---

doc/compiled.json
paths/keys/search.yaml
paths/search/in_account.yaml
paths/translations/search.yaml

Reverts phrase/openapi#702
due to invalid commit message (not sure how it got there), it was not picked up by release-please. will re-merge with proper commit message.

chore: Revert "feat(API): Add Pagination header to POST search endpoints [#457]"

---

doc/compiled.json
paths/uploads/create.yaml

https://memsource.slack.com/archives/C02QV9K8EP5/p1732020776325509?thread_ts=1732017394.717759&cid=C02QV9K8EP5

docs: Link to format list

---

doc/compiled.json
paths/comment_replies/create.yaml
paths/comments/create.yaml

https://phrase.atlassian.net/browse/STRINGS-866

fix(API): Comment creation schema fix #STRINGS-866

---

doc/compiled.json
paths/repo_syncs/export.yaml
paths/repo_syncs/import.yaml

chore(docs): Remove beta for repo sync API

---

openapi-generator/templates/go/README.mustache
openapi-generator/templates/go/go.mod.mustache

Unfortunately `x-release-please-major` didn't work

fix(go): go v4 module bump

---

clients/go/test/api_custom_metadata_test.go
clients/go/test/api_jobs_test.go
clients/go/test/api_locales_test.go
clients/go/test/api_uploads_test.go

Also bump go module version in tests

fix(go): Fix go module in tests

---

doc/compiled.json
schemas/job_details.yaml

Add source_translations_updated_at timestamp to jobs, showing last updated at from translations of job keys in the given source language.
Any affected ticket/issue:
- https://phrase.atlassian.net/browse/STRINGS-719

feat(API): Add source last updated at information on job details

---

.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/release-please.yml

Adjust workflow triggers for main branch after rename from master.

build: Adjust workflow triggers for main branch

---

doc/compiled.json
parameters.yaml
paths/jobs/index.yaml
paths/jobs/index_account.yaml

For https://phrase.atlassian.net/browse/STRINGS-1555 we need to reduce the volume of the list of jobs queried. This enables us to narrow down the list only to recently updated jobs.

feat(API): add updated_since filter to job list #STRINGS-1555

---

clients/ruby/.github/workflows/release.yml

Ruby pipeline is failing for some time https://github.com/phrase/phrase-ruby/actions/runs/13458010727/job/37606219426

build(ruby): update setup-ruby action version

---

.github/workflows/test-cli.yml

Build CLI app in CI to avoid introducing changes that crash the Go build.
https://phrase.atlassian.net/browse/STRINGS-536

build(CLI): Build CLI app in CI [STRINGS-536] 

---

doc/compiled.json
paths/comment_replies/index.yaml
paths/comments/index.yaml

- https://phrase.atlassian.net/browse/STRINGS-1910
Remove falsy request body from GET comments

fix(API): Remove request body from GET comments

---

README.md

Clarify further how to compose the PR titles.

docs: Further explain PR title naming

---

clients/java/src/test/java/com/phrase/client/api/UploadsApiTest.java
doc/compiled.json
paths/uploads/create.yaml

Extend uploads#create API by `verify_mentioned_translations` parameter
- https://phrase.atlassian.net/browse/STRINGS-2282

feat(API): Add "verify_mentioned_translations" parameter to uploads

---

doc/compiled.json
paths.yaml
paths/translations/batch_unreview.yaml
paths/translations/unreview.yaml

- Adding translations unreview & batch unreview to API docs
- https://phrase.atlassian.net/browse/STRINGS-2360

feat(API): Translations unreview & batch unreview

---

doc/compiled.json
paths/tags/show.yaml

- Document `omit_statistics` param on tags#show

feat(API): Add omit_statistics param to tags#show

---

.github/workflows/test-ruby.yml
clients/java/src/test/java/com/phrase/client/api/LocalesApiTest.java
clients/ruby/.license-decisions.yml
doc/compiled.json
paths/locale_downloads/create.yaml
paths/locales/download.yaml

Add new download parameter `updated_since` to filter for recently changed translations

feat(API): add updated_since param for downloads

---

README.md

Make it explicit what the final step is in bringing changes live.

docs: clarify deployment final step in README
